roles:
  - name: nginxinc.nginx
    version: 0.24.1
  - name: nginxinc.nginx_config
    version: 0.7.0
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.2.0